### ISSUE TITLE
Can't control H103

### ISSUE THREAD

**Issue by emilyboda** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#48]
Hi! I installed octoprint recently and I can't seem to get this plug-in to work. I have a H103. 

I've verified that my IP address is correct and followed the directions (inputting IP address, restarting, clicking "show configuration"). When I click "show configuration" it tells me my device name and firmware version, and I have "auto shutdown" enabled. However, it does not auto shutdown after a print. Also, I can't turn it on or off with the buttons in the nav bar. 

I'm able to control this plug with Kasa and also with my Google Home, so I'm not sure what's going on. I first installed the plug-in a few days ago with the previous version (1.0.2?) and today updated to v1.0.3 and I still can't get it to work. Any troubleshooting tips? I noticed there were some other issues with H103, not sure if my problems are related.

**Comment by jamesmccannon02** [comment]
Hi, I believe this was an issue for new users. It is now fixed in v1.0.3 but you have to fully remove/uninstall the software and then re-install it. Then re-follow the setup instructions within the settings section of the plugin. This should work. Just remember uninstall & cleanup

**Comment by emilyboda** [comment]
Thanks for the quick response! What do you mean by "clean up"? Is there a link to some instructions you can provide? Just want to make sure I do it right the first time.

**Comment by ppriest** [comment]
To resolve it for me I completely uninstalled the plugin, restarted octoprint, reinstalled it (I had to clear a cache under advanced options for it to pickup on 1.0.3), and reconfigure it. For good measure I set the IP and type, then Saved, restarted Ocotprint again, and then configured the further settings.

**Comment by jamesmccannon02** [comment]
@ppriest Thanks for providing community support. Helps a lot. @emilyboda this if you follow the instructions above it will fix the issue 95% of the time.

**Comment by emilyboda** [comment]
Hey! I followed the above instructions and I'm still not able to control my plug with the buttons in octoprint and it doesn't auto shutdown at the end of the print, even though I have that option checked. 

My steps:
1. I uninstalled the plug in (did the "clean up")
2. Restarted the whole pi
3. reinstalled the plug in **(couldn't find the options to clear cache anywhere)**
4. set my IP
5. restarted the pi again
6. clicked the settings and saw the info for my plug

Maybe the problem is because I didn't clear the cache like @ppriest suggested. I couldn't find any menu in the octoprint settings called "advanced options" and I didn't find any advanced options in the plug in settings either. Can anyone help?

**Comment by jamesmccannon02** [comment]
If the information is being filled in then I believe this might be an issue that was brought up by a user yesterday. He found the issue was with a naming conflict with other OctoPrint Plugins. I am working to fix this over the weekend and will let you know when it is finished. If you are aware how to change the code all that needs done is to change the ``type`` variable to `deviceType`` and this should solve the problem. Else I will release a fix ASAP

**Comment by emilyboda** [comment]
I changed the settings and it's still not working!

Here's what I did:
1. ssh into the pi
2. cd .octoprint
3. nano config.yaml
4. Change the word "type" under the name of the plugin to "deviceType" 
5. save the file and reboot the pi
6. Once the pi was rebooted, I attempted to turn off the outlet using the buttons in the octoprint header, but it didn't work.
6. Go to the plugin settings and click "save configuration". I noticed it now said "unknown" again.
7. reboot the pi
8. I attempted to turn off the outlet by using the turn off button in the header and it didn't turn the printer off.
9. I ssh'd back into the pi again just to make sure my settings saved. Now, I see the line I edited from type to deviceType, but the plugin seems to have added the old line back underneath so now there's two lines!

![tplink](https://user-images.githubusercontent.com/9170143/112879167-d0f2cf80-9096-11eb-858c-e3246bb43e3d.PNG)

**Comment by jamesmccannon02** [comment]
Hi, This is a more complex issue than that. The naming style has to change within the code as well as the storage file for that data. Else it still tries to call the type command. I have it mostly fixed at the moment. Will post when it it fixed.

**Comment by jamesmccannon02** [comment]
@emilyboda So this hasn't been pushed as a full release yet because i am trying to find a way that all my current users don't have to re-configure their setup before a full release. But if you follow the manual installation instructions it should bring through the version 1.0.5.

**Comment by emilyboda** [comment]
Ok, I'm printing something atm but I will reinstall tonight. I just follow the "manual installation" instructions in the readme, right?

**Comment by jamesmccannon02** [comment]
Yes thats correct. Then check within the plugin manager that it is version 1.0.5 that has come through. You will need to have uninstalled and cleaned up the version 1.0.4 to get back to a clean slate. Just done this myself and worked for me so i hope it is the same for yourself.

**Comment by emilyboda** [comment]
Hey James-

I got the plugin updated to 1.0.5. I made sure to clean up data and also reboot the pi several times. It is still not turning off or on. Again, I can control it with Google Home and other apps, but not this one. Here's what my logs look like:

```
2021-04-05 10:55:31,889 - octoprint.plugins.TpLinkAutoShutdown - INFO - {'url': '192.168.1.252', 'deviceType': 'smartPlug', 'command': 'update'}
2021-04-05 10:55:31,925 - octoprint.plugins.TpLinkAutoShutdown - INFO - {'sw_ver': '1.1.3 Build 200804 Rel.095135', 'hw_ver': '2.1', 'mac': '3[actual mac address omitted]E', 'mic_type': 'IOT.SMARTPLUGSWITCH', 'hwId': '1[actual numbers omitted]A', 'oemId': '2[actual numbers omitted]8', 'dev_name': 'Smart Wi-Fi Plug Lite'}
2021-04-05 10:55:40,710 - octoprint.plugins.TpLinkAutoShutdown - INFO - Turning the printer OFF
```

**Comment by jamesmccannon02** [comment]
Hi, the plugin seems to be doing what it should be doing so i am a little unsure why this issue is still happening. However, you no longer are on the latest version. This version is v1.0 and now we are on v1.1.2. This is working as intended so please try that. Else it may be an issue regarding the firmware on the plug. Try updating the plug firmware and if that doesn't work I am unsure what the issue is. However if you find it please mention as I can then look at how I can fix the issue in the background. Interfacing with these plugs isn't the easiest as they aren't designed with OctoPrint in mind

**Comment by emilyboda** [comment]
James,

I've updated the plugin to the most recent version (1.1.2) after uninstalling and cleaning the old plugin. I checked for firmware updates for my smart plug and it's up to date. I'm still not able to turn off the printer from octoprint and it does not shut down after finishing a print. I also tried connecting a second plug I have, purchased at the same time as the first plug, and I can't get octoprint to control that one either. The logs seem to say everything is working normally, but the plugs do not turn on or off.

**Comment by emilyboda** [comment]
Hey James-

I wanted to let you know it finally worked! After posting my last comment I printed a ~14 hr print and the printer did not turn itself off after, but then this morning I leveled the bed with a quick print and the printer turned off immediately after! I have no idea what changed but this is great!
